# Generated by Django 4.2.16 on 2024-12-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(error_messages={'max_length': 'Max session token length is 200 characters', 'null': "Session token can't to be empty", 'unique': 'This token is already existing'}, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id', 'session_token'],
            },
        ),
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, error_messages={'null': "Attempt count can't to be empty"})),
                ('users', models.ManyToManyField(to='dashboard.user')),
            ],
            options={
                'db_table': 'attempts',
                'ordering': ['id', 'count'],
            },
        ),
    ]
